# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12a7470cffd9f03a8ca43dc3ef73f8121fd3f99152d58995e92209e14a16b29b273c51558f52a716473a98e9c2664d3a34543cee1cf8516c118824bc7bbf5f22

test:
  secret_key_base: 39c959583dd66e1bb6f3f65b2f3e32abc9eae3d76294e70c59b7f9f0aecef95e2ca86ac4f4bc16ced62071d0d1d4c45cce6c0fc5e0f50344ed0d3d3325d6c111

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
